### ISSUE TITLE
wf-app able to run workflow

### ISSUE THREAD

**Issue by fyhao** [fyhao/wf-gateway#16]
Objective: wf-app able to receive configuration update, then in runtime register / unregister the endpoints, then able to execute workflow after make a HTTP request to that endpoint.

Tasks:
------
- [x] Depends on wf-app to receive configuration update, deployAll #10 
- [x] wf-app control module manage endpoint routing in runtime https://github.com/fyhao/wf-gateway/issues/17
- [x] wf-app to execute workflow based on defined request endpoint https://github.com/fyhao/wf-gateway/issues/18
