### ISSUE TITLE
Initial Tasks - Infrastructure setup

### ISSUE THREAD

**Issue by fyhao** [fyhao/wf-gateway#2]
In order to support initial objective, below are the main tasks to develop in first milestone.

Tasks:
------
- [x] Create 3 sub folder for individual node.js based apps. ServiceControl, AppInstance, WebAdmin
- [x] Each contains own package.json, unit test scripts, dockerfile
- [x] Create fourth folder for integration test scripts, e2e tests.
- [x] ServiceControl (wf-control) https://github.com/fyhao/wf-gateway/issues/3
- [x] AppInstance (wf-app) https://github.com/fyhao/wf-gateway/issues/4
- [x] WebAdmin (wf-admin) https://github.com/fyhao/wf-gateway/issues/5
- [x] ServiceController create basic backend store interface and implement JSON file based first. https://github.com/fyhao/wf-gateway/issues/6
- [x] ServiceController support configure backend database mysql
- [x] ServiceController Able to create app https://github.com/fyhao/wf-gateway/issues/7
- [x] ServiceController Able to create HTTP based API endpoint for listeners, assigned to app, and able to support basic request & workflow & response https://github.com/fyhao/wf-gateway/issues/8
- [x] ServiceController Able to create workflow https://github.com/fyhao/wf-gateway/issues/9
- [x] ServiceController Able to create server instance, not tied to apps. App and instances are many to many relationship. https://github.com/fyhao/wf-gateway/issues/14
- [x] ServiceController Able to push down configuration to app instance https://github.com/fyhao/wf-gateway/issues/10
- [x] App Able to run workflow https://github.com/fyhao/wf-gateway/issues/16
(TBC for App and web, at least app can execute workflows)
- [x] Basic workflow engine implementation https://github.com/fyhao/wf-gateway/issues/21

- [x] Basic Integration Test, e2e Test https://github.com/fyhao/wf-gateway/issues/11 (API E2E done, UI E2E not done)
- [x] Travis CI e2e test https://github.com/fyhao/wf-gateway/issues/25
